drop table if exists member CASCADE;
create table member
( id bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);

drop table if exists ingredient CASCADE;
create table ingredient
( id bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);


drop table if exists meal CASCADE;
create table meal
( id bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);
